name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Publish package
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
        run: deno i && deno publish
